<a href="https://colab.research.google.com/github/AbdellatifAlbanna/Data-analysis-1/blob/main/23_2_2024%2CLec_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
#this code created by me on 23/02/2024 to test all phython codes
#reference ,kaggle (hello,python and learn pandas)


import math
import pandas as pd
import numpy as np



df = pd.read_csv('/content/sample_data/california_housing_train.csv')



#df.loc[(df.housing_median_age == 15.0) & (df.total_bedrooms >= 10)]


#df.loc[(df.housing_median_age == 15.0) | (df.total_bedrooms >= 10)]

#df.loc[df.housing_median_age.isin([15.0,19.0])]


# df.loc[df.housing_median_age.isin([15.0, 19.0])]


#df.loc[df.housing_median_age.isnull()]

# reviews['critic'] = 'everyone'

# df.head()

#df.rename(columns={'total_rooms': 'totalr'})

# pd.concat([canadian_youtube, british_youtube])
# canadian_youtube = pd.read_csv("/content/sample_data/california_housing_train.csv")
# british_youtube = pd.read_csv("/content/sample_data/california_housing_test.csv")


# pd.concat([canadian_youtube, british_youtube])

#df.total_rooms.unique()
#df.total_rooms.value_counts()
# df.groupby('total_rooms').total_rooms.count()

#df.groupby(['total_rooms']).total_rooms.agg([len, min, max])

df.sort_values(by='total_rooms',ascending=False)

# df[pd.isnull(df.longitude)]


# df.longitude.fillna("Unknown")

# df.longitude.replace("124.26", "99")

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2871,-117.74,33.89,4.0,37937.0,5471.0,16122.0,5189.0,7.4947,366300.0
12772,-121.79,36.64,11.0,32627.0,6445.0,28566.0,6082.0,2.3087,118800.0
2969,-117.78,34.03,8.0,32054.0,5290.0,15507.0,5050.0,6.0191,253900.0
8881,-118.78,34.16,9.0,30405.0,4093.0,12873.0,3931.0,8.0137,399200.0
1116,-117.12,33.52,4.0,30401.0,4957.0,13251.0,4339.0,4.5841,212300.0
...,...,...,...,...,...,...,...,...,...
4502,-118.04,33.90,36.0,15.0,5.0,15.0,6.0,0.4999,162500.0
15369,-122.29,37.81,46.0,12.0,4.0,18.0,7.0,0.4999,67500.0
8188,-118.44,34.28,46.0,11.0,11.0,24.0,13.0,2.8750,162500.0
16309,-122.50,37.79,52.0,8.0,1.0,13.0,1.0,15.0001,500001.0
2990,-117.79,35.21,4.0,2.0,2.0,6.0,2.0,2.3750,137500.0